### ISSUE TITLE
System Agnostic?

### ISSUE THREAD

**Issue by Thornbrier** [surged20/wjmais#11]
I've only just found WJ:MAiS because of your module, but from what I see the content is intended to be usable in any fantasy setting. That does not appear to be the case for this module. Just wanted to be sure, but I assume it is using some content from the dnd5e core module since I am unable to use it in my pf2e game world.

**Comment by surged20** [comment]
WJ:MAiS has lore that's generic enough to be used in any fantasy setting.There's certainly been a few attempts in the past to convert Spelljammer to pf1e.
However, the most significant part of WJ:MAiS is the 5e-specific mechanics for ship combat, crew actions, spells, etc which are implemented in this module. Because of this, the wjmais module is specifically only compatible with the dnd5e system. The mechanics aren't usable in pf2e without a complete rewrite of the WJ:MAiS PDF rules content.

**Comment by surged20** [comment]
Probably a stronger reason that this is released only for a D&D system is that the WotC fan content license allows us to only use this content (artwork, etc.) for WotC games. Strict compliance with the fan content license is required for the module to be included in the Foundry VTT package system.
